package main

// Manifest constants. Do not edit this file. Values are replaced by make.
const (
	Version           = "SYSFLOW_VERSION"
	JSONSchemaVersion = "JSON_SCHEMA_VERSION"
	BuildNumber       = "BUILD_NUMBER"
)
