//
// Copyright (C) 2020 IBM Corporation.
//
// Authors:
// Frederico Araujo <frederico.araujo@ibm.com>
// Teryl Taylor <terylt@ibm.com>
//
package main

// Manifest constants. Do not edit this file. Values are replaced by make.
const (
	Version           = "0.1.0"
	JSONSchemaVersion = 1
	BuildNumber       = "1"
)
